title: iAInNet's Blog
author:
  name: iAInNet
  email: lastdayinworld2012@gmail.com
description: >
  Stay Hungry, Stay Foolish.

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

header_pages:
  - index.md
  - category.md
  - about.md

minima:
  skin: classic

categories:
  - 构建自我实现和管理体系
  - 构建跨越时间的信息处理体系
  - 分布式存储系统设计与实现

google_analytics: G-6YERGBY4FK

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
